server:
  # https加密端口号443
  port: 443
  # SSL证书路径(一定要加上classpath:)
  ssl:
    key-store: classpath:zjutleo.cn.jks
    # SSL证书密码(密码在keystorePass.txt文件中)
    key-store-password: sggpjc477pm
    # 证书类型
    key-store-type: JKS
  servlet:
    context-path: /health

# 本地测试端口
#server:
#  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/health_server?serverTimezone=Hongkong&characterEncoding=utf8
    username: root
    password: 330800Abc/
#    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 330800abc
#    password: 330800
  data:
    redis:
      repositories:
        enabled: false
  jackson:
    time-zone: GMT+8
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapperxml/*.xml
wechat:
  appid: wxdccc706101e815e2
  secret: 7021269e9e483c0ee2e4f2af5cb6c53d
jwt-config:
  secret: zjutLeo001212leoPatricy
  expireTime: 0x7fffffff
#  expire-time: 1800
  refreshTokenExpireTime: 604800
user-operation-log:
  format: '[{}][{}][{}]'